### PR TITLE
Update part2 data

### PR DESCRIPTION
**Pull request by tpimentelms**

### CODE REVIEW

**Comment by tpimentelms** [comment]
Closes #9 and #13

**Comment by LinguList** [comment]
@tpimentelms, question, are the segmentations in those cases, where they were made originally (Russian, German) also re-segmented with LingPy, or are they just kept? Since LingPy does handle dipthongs in a greedy way (not what we want) and cannot detect affricates like `ts`, it is important to make sure that one has the best version here. 

I'd also suggest to run against CLTS, indicated in #12, to make sure we have features and type-token lists.

**Comment by LinguList** [comment]
For the German data I sent yesterday, this has already been done, so the type-tokens are in my opinion unproblematic, and all data follow CLTS standards.

**Comment by LinguList** [comment]
Sorry, just saw that you used the segmentation I provided for German. So the question remains for Russian, where data were also segmented.

**Comment by tpimentelms** [comment]
They were kept @LinguList . I only segmented the ones with no previous segmentation.
I sent the CLTS analysis files to you via email.

**Comment by LinguList** [comment]
Ah, sorry, there were too many files, and I have slow internet, so I'll check now!

**Comment by tpimentelms** [comment]
Closes #12

**Review by LinguList — APPROVED** [review]

**Comment by tpimentelms** [comment]
This PR:
* Updates all part2 data.
* Uplodes german data.
* Adds IPA segmentations.

**Pull request merged**
